name: RrSubs
version: '1.0-SNAPSHOT'
main: dev.portalgenesis.rrSubs.RrSubs
api-version: '1.21'
<<<<<<< HEAD
depend: [CommandAPI]
authors: [ Izero ]
commands:
  rrsubs:
    description: Управление подписками (pro/deluxe)
    usage: /rrsubs <give|see|reload>
    permission: rrsubs.admin
=======
authors: [ Izero ]
>>>>>>> 959433715ead53dbce4b84c9baeb307d745f6525
